# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escritorio', models.CharField(max_length=120)),
                ('servico', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('data', models.DateField()),
                ('situacao', models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado'), ('E', 'Em Andamento')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_cliente', to='core.Cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_escritorio', to='core.Escritorio')),
            ],
            options={
                'ordering': ('data', 'horario'),
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=10)),
                ('profissao', models.CharField(max_length=120)),
                ('gerente', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('A', 'Ausente'), ('D', 'Disponível'), ('O', 'Ocupado')], default='A', max_length=1)),
                ('escritorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.Escritorio')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('andar', models.CharField(max_length=2)),
                ('escritorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='core.Escritorio')),
            ],
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_profissionais', to='core.Profissional'),
        ),
    ]
