# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='andar',
        ),
    ]
