# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sala_andar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='descricao',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
