# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sala_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
