# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profissional_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemagenda',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.Profissional'),
        ),
    ]
