# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170907_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
